// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kcemsdbabjkqaduzoabs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtjZW1zZGJhYmprcWFkdXpvYWJzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI5MDI5MzIsImV4cCI6MjA1ODQ3ODkzMn0.bzD52jerdskNS2bUc3CCBHgJg8pM0y_6nuZ8ZIA1EHo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);